var data,response,countFunction,isExplorer;function init(){observation();if(/MSIE/g.test(navigator.userAgent)){isExplorer=true;iestyle()}$$("a.logo")[0].setStyle({border:0,textDecoration:0,color:"transparent"});if($(document.body).hasClassName("welcome")&&getGetArgument("c")==1){$("confirm").scrollTo();$("confirm").focus()}}
function observation(){$("confirm")&&$("confirm").observe("click",confirmation);$("logout")&&$("logout").observe("click",logout);$("wrapper").observe("click",catchClickTimes)}
function confirmation(a){if(a.element().hasClassName("maxed")){if(($(document.body).hasClassName("welcome")?true:confirm("Are you sure you want to move to the next section?\r\n (There is no way to return to this page.)"))==true){loading();data={confirm:"yes"};a=getActivityById(aid?aid:1);placeRequest(a,data)}}else{a="Please select "+(max-countFunction()).toString()+" more option(s).";alert(a)}}
function rate_init(){counter==max?activateButton(1):activateButton(0);countFunction=countRatings;document.observe("click",function(a){a=Event.element(a);if(a.hasClassName("compatible")||a.hasClassName("choice")){var b=Object.isElement(getParentByClassName(a,"repeat")),c=getParentByClassName(a,"ratingRow"),d=a.hasClassName("compatible")?a:a.childElements()[0];data={crid:c.id.split("-")[0].replace("r",""),coid:c.id.split("-")[1],rating:d.innerHTML,uid:uid,pop:"stay",repeat:b,confirm:"no",elapsed:stopWatch,
clickCount:clickCounter};postRequest("rate",data);setBooleanClassName(c,a.parentNode)}countRatings()==max?activateButton(1):activateButton(0)})}
function compare_init(){counter==max?activateButton(1):activateButton(0);countFunction=countComparisons;document.observe("click",function(a){a=Event.element(a);if(a.hasClassName("compatible")||a.hasClassName("choice")){var b=a.hasClassName("compatible")?a.parentNode:a;fid=fid?fid:0;data={cell:b.id,uid:uid,fid:fid,pop:"stay",confirm:"no",elapsed:stopWatch,clickCount:clickCounter};b=b.parentNode;postRequest("compare",data);setBooleanClassName(b,a.parentNode)}countComparisons()==max?activateButton(1):
activateButton(0)})}
function select_init(){counter==max?activateButton(1):activateButton(0);countFunction=countSelections;document.observe("click",function(a){a=Event.element(a);if(a.hasClassName("compatible")||a.hasClassName("choice")){var b=a.hasClassName("compatible")?a:a.childElements()[0];a=b.parentNode;b=b.id.replace(/[A-z]+/g,"");if(a.hasClassName("false")){if(counter==max)return false;data={cid:b,uid:uid,fid:fid,value:"true",pop:"stay",confirm:"no",elapsed:stopWatch,clickCount:clickCounter};postRequest("select",
data);a.removeClassName("false");a.addClassName("true");counter++}else{data={cid:b,uid:uid,fid:fid,value:"false",pop:"stay",confirm:"no",elapsed:stopWatch,clickCount:clickCounter};postRequest("select",data);a.removeClassName("true");a.addClassName("false");counter--}}counter==max?activateButton(1):activateButton(0)})}
function postRequest(a,b){var c=$H(b).toJSON();new Ajax.Request("./php/scripts/switchboard.php",{parameters:{action:a?a:"",args:c},onSuccess:function(d){response=d.responseText}});return null}function placeRequest(a,b){var c=$H(b).toJSON();new Ajax.Request("./php/scripts/switchboard.php",{parameters:{action:a?a:"",args:c},onSuccess:function(){window.location="."}});return null}
function getParentByClassName(a,b){for(var c=0;c<a.ancestors().length;c++)if(a.ancestors()[c].hasClassName(b))return a.ancestors()[c];return null}function setBooleanClassName(a,b){for(var c=a.childElements(),d=0;d<c.length;d++)c[d].removeClassName("true");b.addClassName("true")}function countComparisons(){for(var a=0,b=$$("table.entry")[0].childElements()[1].childElements(),c=0;c<b.length;c++)for(var d=b[c].childElements(),e=0;e<d.length;e++)if(d[e].hasClassName("true")){a++;break}return a}
function countRatings(){for(var a=0,b=$$("table.entry"),c=0;c<b.length;c++)for(var d=b[c].childElements()[0].childElements(),e=0;e<d.length;e++)for(var g=d[e].childElements(),f=0;f<g.length;f++)if(g[f].hasClassName("true")){a++;break}return a}function countSelections(){return counter}function activateButton(a){if(a<1){$("confirm").removeClassName("maxed");$("confirm").addClassName("notmaxed")}else{$("confirm").removeClassName("notmaxed");$("confirm").addClassName("maxed")}return"Success"}
function getActivityById(a){return a==1?"select":a==2?"compare":"rate"}
function logout(){if(confirm("Do you want to logout? \n(You can always come back later.)")){for(var a=$("content").descendants(),b=0;b<a.length;b++)a[b].tagName=="TABLE"&&a[b].remove();$("rate")&&$("rate").remove();$$("h2")[0].innerHTML="Goodbye";$$("p.instructions")[0].innerHTML="Please reuse the original link to complete the survey.";$$("p.instructions")[0].insert({after:"Thank you for participating, please return to complete the survey whenever you have a chance."});$$("div.foot")[0].setStyle({top:"",
bottom:10});$("logout").remove();$("confirm").remove();document.stopObserving()}}function loading(){var a='<div id="waiting" class="loading">';a+='<img src="./styles/images/ajax_load.gif" title="Please stand by." />';a+="</div>";$("content").hide();$("wrapper").insert(a);a=$("waiting").childElements()[0];a.setStyle({marginLeft:($("wrapper").getWidth()-a.getWidth())/2});isExplorer&&a.setStyle({marginTop:($("wrapper").getHeight()-a.getHeight())/2});return"Success"}
var _watch=0,_timer,_beginTiming=0,currentTime=0,lastTime=0,stopWatch=0,clickCounter=0;function catchClickTimes(a){if(a.element().hasClassName("compatible")){clickCounter++;stopWatch=currentTime-lastTime;lastTime=currentTime;beginTiming();return"Caught"}return false}function beginTiming(){if(_beginTiming<1){_beginTiming=1;timer()}}function timer(){currentTime=_watch;_watch++;_timer=setTimeout(timer,1)}
function getGetArgument(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return a==null?"":a[1]}
function iestyle(){var a=$("content").getHeight()>500?$("content").getHeight():500;$("wrapper").setStyle({height:a});$("content").setStyle({width:"98%",clear:"both",marginRight:0});$$("div.details")[0]&&$$("div.details")[0].setStyle({clear:"both",zIndex:10});$$("div.topLeft")[0].setStyle({backgroundPositionY:3,top:-3,height:1});$$("div.topRight")[0].setStyle({backgroundPositionY:3,top:-3,height:1});$$("div.bottom")[0].setStyle({bottom:5-$$("div.bottom")[0].getHeight()});$$("hr.decor")[0].setStyle({height:3,
top:-5,left:-10,zIndex:3});$$("p.instructions").length>0&&$$("p.instructions")[0].setStyle({top:-45});if($("status")){var b=($("content").getWidth()-$$("hr.statusHolder")[0].getWidth())/2;$("status").setStyle({left:b,bottom:-20});$$("hr.statusViewer")[0].setStyle({top:$$("hr.statusHolder")[0].getHeight()})}$$("div.foot")[0]&&$$("div.foot")[0].setStyle({position:"static",width:$("content").getWidth()});if($("describe")){$("describe").setStyle({top:a-55});$("status").setStyle({top:a-60})}if($("confirm")&&
$("logout"))$("confirm").setStyle({right:30});else $("confirm")&&$("confirm").setStyle({zIndex:11,position:"relative",left:$("content").getWidth()-100});b=$$("a.compatible");for(a=0;a<b.length;a++)b[a].setStyle({color:b[a].ancestors()[0].getStyle("color")});$$("div.faqme a")[0].setStyle({filter:"progid:DXImageTransform.Microsoft.BasicImage(rotation=1)"});$$("div.faqme")[0].setStyle({top:40,right:0,position:"absolute"});b=$$("div.build table.entry tbody tr td a.compatible");for(a=0;a<b.length;a++)b[a].setStyle({color:"#333"})}
;